### ISSUE TITLE
suggestion: include info about the in-app account setup on your website

### ISSUE THREAD

**Issue by hanleybrand** [oslabs-beta/kaptn#50]
I was surprised after installing at being prompted to create an account, as far as can find there's no mention of needing an account on the website, and it wasn't clear where the account was managed or what it was for (i.e. is it for a cloud backup of the app config, do generated yaml files get uploaded somewhere, is it for using k8syaml.com, is it just for interacting with the local Kaptn server, etc).  

I put a pause on going forward since that wasn't clear (didn't make an account) -- it looks like the answer might be that it's a local account, but it would be good to explain the what and why of the account for people who download the app

**Comment by ohodel** [comment]
Thanks for bringing this to our attention - and for your interest in Kaptn! We have disabled the login feature for now since saving information to a user's account is currently still in progress. To use our app, just click "Continue as guest" to access all the features of Kaptn. We added a note to our ReadMe to specify for new users.
