### ISSUE TITLE
Possible name clash keptn - kaptn

### ISSUE THREAD

**Issue by kkapelon** [oslabs-beta/kaptn#62]
See also

https://github.com/keptn

https://lifecycle.keptn.sh/

**Comment by brecht-horn** [comment]
Hi there,

Thanks for bringing that to our attention!

We chose the name "Kaptn" because Kubernetes is Greek for commander/helmsman, and we thought Captain spelled "Kaptn" was a fun wordplay on that.

Hopefully since keptn offer a different product and have a different reason for their name, we will be okay. But if the issue persists, we are happy to be made aware now! 

Thanks again, and closing this for now.
